services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped

    cpus: 2
    pids_limit: 256
    mem_limit: 1024m
    environment:
      - NUM_WORKERS=4

    depends_on:
      - mongodb


  mongodb:
    image: mongo:7.0.2
    volumes:
      - dbdata:/data/db
    restart: unless-stopped

volumes:
  dbdata: